import chromadb


class VectorStore:

    def __init__(self):

        self.client = chromadb.PersistentClient(          #It is helps the store data permenently on disk
            path="Vector_Store"
        )

        self.collection = (                             #Create a collection like the table in a RDBMS
            self.client.get_or_create_collection(
                name="mediassist_docs"
            )
        )

    def add(
        self,
        ids,                     #Id for the unique document id
        documents,                #The actual text content of the document
        embeddings,              #The vector representation of the document, typically generated by an embedding model
        metadatas                #Additional information about the document, such as source, date, or any other relevant metadata
    ):

        self.collection.add(                              
            ids=ids,
            documents=documents,
            embeddings=embeddings.tolist(),        #Convert the embeddings to a list format suitable for storage in the vector database of ChromaDB
            metadatas=metadatas
        )

    def search(
        self,
        query_embedding,   # The vector representation of the search query, generated by the same embedding model used for the documents
        k=10               # Return the top k most similar documents
    ):

        return self.collection.query(
            query_embeddings=[
                query_embedding.tolist()
            ],
            n_results=k,
            include=["documents", "distances", "metadatas"]
        )